apiVersion: v1
kind: Service
metadata:
  name: dock
  labels:
    app.kubernetes.io/name: dock
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dock
  ports:
    - name: http
      port: 80
      targetPort: http
